# serverless.yml

service: api-pumpkin

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: api_pumpkin/app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.7
  region: us-east-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
